language: python
python:
  - '3.4'
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
install: 'pip install -r requirements.txt'
script: 'make all'
notifications:
  email: false
