# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('domesticated', models.FloatField()),
                ('naturalized_where_grown', models.FloatField()),
                ('weedy_races', models.FloatField()),
                ('tropical_suitable_climate', models.FloatField()),
                ('suitable_climate_quality', models.FloatField()),
                ('broad_suitable_climate', models.FloatField()),
                ('tropical_naturalized', models.FloatField()),
                ('repeated_history_introduction', models.FloatField()),
                ('naturalized_beyond_natural', models.FloatField()),
                ('garden_weed', models.FloatField()),
                ('agricultural_weed', models.FloatField()),
                ('environmental_weed', models.FloatField()),
                ('congeneric_weed', models.FloatField()),
                ('spines_production', models.FloatField()),
                ('allelopathic', models.FloatField()),
                ('parasitic', models.FloatField()),
                ('unplatable_grazing_animals', models.FloatField()),
                ('toxicity_animals', models.FloatField()),
                ('pests_or_pathogens_host', models.FloatField()),
                ('alleric_or_toxic_humans', models.FloatField()),
                ('fire_hazard', models.FloatField()),
                ('shade_tolerant', models.FloatField()),
                ('soil_conditions_tolerance', models.FloatField()),
                ('climbing_growth_habit', models.FloatField()),
                ('dense_thickets', models.FloatField()),
                ('aquatic', models.FloatField()),
                ('grass', models.FloatField()),
                ('nitrogen_fixing_woody', models.FloatField()),
                ('geophyte', models.FloatField()),
                ('reproductive_failure_native_habitat', models.FloatField()),
                ('viable_seed', models.FloatField()),
                ('hybridizes_naturally', models.FloatField()),
                ('apomictic', models.FloatField()),
                ('requires_specialist_pollinators', models.FloatField()),
                ('vegetation_fragmentation_reproduction', models.FloatField()),
                ('minimum_generative_time', models.FloatField()),
                ('likely_unintentional_dispersal', models.FloatField()),
                ('human_intentional_dispersal', models.FloatField()),
                ('likely_produce_containment_dispersal', models.FloatField()),
                ('adapted_to_wind_dispersal', models.FloatField()),
                ('water_dispersal', models.FloatField()),
                ('bird_dispersal', models.FloatField()),
                ('animal_dispersal', models.FloatField()),
                ('survive_passage_through_gut', models.FloatField()),
                ('prolific_seed_production', models.FloatField()),
                ('persistent_propagule_bank', models.FloatField()),
                ('well_controlled_herbicides', models.FloatField()),
                ('tolerates_fire', models.FloatField()),
                ('natural_enemies_present', models.FloatField()),
            ],
        ),
    ]
