from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Plant(models.Model):
	name = models.CharField(max_length = 1000)
	domesticated = models.FloatField(null=True, blank=True)
	naturalized_where_grown = models.FloatField(null=True, blank=True)
	weedy_races = models.FloatField(null=True, blank=True)
	tropical_suitable_climate = models.FloatField(null=True, blank=True)
	suitable_climate_quality = models.FloatField(null=True, blank=True)
	broad_suitable_climate = models.FloatField(null=True, blank=True)
	tropical_naturalized = models.FloatField(null=True, blank=True)
	repeated_history_introduction = models.FloatField(null=True, blank=True)
	naturalized_beyond_natural = models.FloatField(null=True, blank=True)
	garden_weed = models.FloatField(null=True, blank=True)
	agricultural_weed = models.FloatField(null=True, blank=True)
	environmental_weed = models.FloatField(null=True, blank=True)
	congeneric_weed = models.FloatField(null=True, blank=True)
	spines_production = models.FloatField(null=True, blank=True)
	allelopathic = models.FloatField(null=True, blank=True)
	parasitic = models.FloatField(null=True, blank=True)
	unplatable_grazing_animals = models.FloatField(null=True, blank=True)
	toxicity_animals = models.FloatField(null=True, blank=True)
	pests_or_pathogens_host = models.FloatField(null=True, blank=True)
	alleric_or_toxic_humans = models.FloatField(null=True, blank=True)
	fire_hazard = models.FloatField(null=True, blank=True)
	shade_tolerant = models.FloatField(null=True, blank=True)
	soil_conditions_tolerance = models.FloatField(null=True, blank=True)
	climbing_growth_habit = models.FloatField(null=True, blank=True)
	dense_thickets = models.FloatField(null=True, blank=True)
	aquatic = models.FloatField(null=True, blank=True)
	grass = models.FloatField(null=True, blank=True)
	nitrogen_fixing_woody = models.FloatField(null=True, blank=True)
	geophyte = models.FloatField(null=True, blank=True)
	reproductive_failure_native_habitat = models.FloatField(null=True, blank=True)
	viable_seed = models.FloatField(null=True, blank=True)
	hybridizes_naturally = models.FloatField(null=True, blank=True)
	apomictic = models.FloatField(null=True, blank=True)
	requires_specialist_pollinators = models.FloatField(null=True, blank=True)
	vegetation_fragmentation_reproduction = models.FloatField(null=True, blank=True)
	minimum_generative_time = models.FloatField(null=True, blank=True)
	likely_unintentional_dispersal = models.FloatField(null=True, blank=True)
	human_intentional_dispersal = models.FloatField(null=True, blank=True)
	likely_produce_containment_dispersal = models.FloatField(null=True, blank=True)
	adapted_to_wind_dispersal = models.FloatField(null=True, blank=True)
	water_dispersal = models.FloatField(null=True, blank=True)
	bird_dispersal = models.FloatField(null=True, blank=True)
	animal_dispersal = models.FloatField(null=True, blank=True)
	survive_passage_through_gut = models.FloatField(null=True, blank=True)
	prolific_seed_production = models.FloatField(null=True, blank=True)
	persistent_propagule_bank = models.FloatField(null=True, blank=True)
	well_controlled_herbicides = models.FloatField(null=True, blank=True)
	tolerates_fire = models.FloatField(null=True, blank=True)
	natural_enemies_present = models.FloatField(null=True, blank=True)