import csv
from species.models import Plants

with open("pier_data_wide.csv") as f:
    reader = csv.reader(f)
    for row in reader:
    	_, created = Plants.objects.get_or_create(
			name = row[0],
			domesticated = row[1],
			naturalized_where_grown = row[2],
			weedy_races = row[3],
			tropical_suitable_climate = row[4],
			suitable_climate_quality = row[5],
			broad_suitable_climate = row[6],
			tropical_naturalized = row[7],
			repeated_history_introduction = row[8],
			naturalized_beyond_natural = row[9],
			garden_weed = row[10],
			agricultural_weed = row[11],
			environmental_weed = row[12],
			congeneric_weed = row[13],
			spines_production = row[14],
			allelopathic = row[15],
			parasitic = row[16],
			unplatable_grazing_animals = row[17],
			toxicity_animals = row[18],
			pests_or_pathogens_host = row[19],
			alleric_or_toxic_humans = row[20],
			fire_hazard = row[21],
			shade_tolerant = row[22],
			soil_conditions_tolerance = row[23],
			climbing_growth_habit = row[24],
			dense_thickets = row[25],
			aquatic = row[26],
			grass = row[27],
			nitrogen_fixing_woody = row[28],
			geophyte = row[29],
			reproductive_failure_native_habitat = row[30],
			viable_seed = row[31],
			hybridizes_naturally = row[32],
			apomictic = row[33],
			requires_specialist_pollinators = row[34],
			vegetation_fragmentation_reproduction = row[35],
			minimum_generative_time = row[36],
			likely_unintentional_dispersal = row[37],
			human_intentional_dispersal = row[38],
			likely_produce_containment_dispersal = row[39],
			adapted_to_wind_dispersal = row[40],
			water_dispersal = row[41],
			bird_dispersal = row[42],
			animal_dispersal = row[43],
			survive_passage_through_gut = row[44],
			prolific_seed_production = row[45],
			persistent_propagule_bank = row[46],
			well_controlled_herbicides = row[47],
			tolerates_fire = row[48],
			natural_enemies_present = row[49],
        	)
          