# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PierData',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
                ('json', models.TextField()),
            ],
        ),
    ]
